name: User Story
description: Create a new user story to describe a feature or enhancement.
title: "[Story]: "
labels: ["user-story", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        ## 📘 User Story
        Use this template to describe a feature from the user's perspective.
        Keep it clear, testable, and focused on value.

  - type: input
    id: contact
    attributes:
      label: Product / Stakeholder Contact
      description: Who can answer questions about this story?
      placeholder: ex. product.owner@example.com
    validations:
      required: false

  - type: textarea
    id: story
    attributes:
      label: User Story Statement
      description: Use the standard format.
      placeholder: |
        As a [type of user],
        I want [some goal or action],
        so that [some value or benefit].
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Background
      description: Why is this story needed? What problem does it solve?
      placeholder: Describe the current pain point or gap.
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Business Value
      description: What value does this deliver to the user or business?
      placeholder: Improves usability, reduces errors, enables new capability, etc.
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this story?
      options:
        - Must Have
        - Should Have
        - Nice to Have
      default: 1
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define clear, testable conditions for success.
      placeholder: |
        Given [context],
        When [action],
        Then [expected outcome].

        - [ ] Scenario 1
        - [ ] Scenario 2
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: Implementation Tasks
      description: Break the story down into actionable tasks.
      options:
        - label: Design / UX updates completed
        - label: API or backend changes implemented
        - label: Database or migration changes (if applicable)
        - label: Frontend implementation completed
        - label: Unit tests added or updated
        - label: Integration / E2E tests added or updated
        - label: Documentation updated

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Blockers
      description: Are there any dependencies or blockers?
      placeholder: Other stories, APIs, approvals, data availability, etc.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes / Assumptions
      description: Any extra context, assumptions, or open questions.
      placeholder: Optional
    validations:
      required: false

  - type: checkboxes
    id: dor
    attributes:
      label: Definition of Ready
      description: Confirm this story is ready for development.
      options:
        - label: Acceptance criteria are clear and testable
        - label: Dependencies are identified
        - label: Scope is well understood
        - label: Story is small enough to complete in one sprint

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done
      description: Confirm what must be true for this story to be complete.
      options:
        - label: All acceptance criteria met
        - label: Code reviewed and approved
        - label: Tests passing
        - label: No critical bugs introduced
        - label: Feature validated by product or stakeholder
