// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace IBTS2026.Domain.Entities;

public partial class Incident
{
    public int IncidentId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int StatusId { get; set; }

    public int PriorityId { get; set; }

    public int CreatedBy { get; set; }

    public int? AssignedTo { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Priority Priority { get; set; }

    public virtual Status Status { get; set; }
}