// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IBTS2026.Domain.Entities;

public partial class AuditLog
{
    public int AuditLogId { get; set; }

    public string EntityName { get; set; }

    public int? EntityId { get; set; }

    public string PropertyName { get; set; }

    public string OldValue { get; set; }

    public string NewValue { get; set; }

    public int? ChangedBy { get; set; }

    public DateTime? ChangedAt { get; set; }
}