// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IBTS2026.Domain.Entities;

public partial class Priority
{
    public int PriorityId { get; set; }

    public string PriorityName { get; set; }

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();
}