// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IBTS2026.Domain.Entities.Features.Incidents.Incident;
using System;
using System.Collections.Generic;

namespace IBTS2026.Domain.Entities;

public partial class Status
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Incident> Incidents { get; set; } = new List<Incident>();
}